#+TITLE: Pranav Bhaskar
#+OPTIONS: toc:nil html-preamble:nil html-postamble:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="test.css" />
#+HTML_DOCTYPE: html5

#+HTML: <aside>
#+HTML: <h1 id="name">Pranav Bhaskar</h1>
#+HTML: <h2 id="title">WEB DEVELOPER</h2>
Pune, Maharashtra, India
#+HTML: <div class="links">
- Email: pranavbhaskar17@gmail.com
- GitHub: https://github.com/CoderPrans
- LinkedIn: https://linkedin.com/in/CoderPrans
- Twitter: https://twitter.com/CoderPrans
#+HTML: </div>
#+HTML: <h2>Skills</h2>
 HTML5, CSS3, JavaScript, React.js, GraphQL,
 Node.js, Python, MongoDB, Git, PWAs
#+HTML: <h2>Certifications</h2>
#+HTML: <div class="certificates">
- Front End Libraries, FreeCodeCamp
  - https://www.freecodecamp.org/certification/coderprans/front-end-libraries
- Responsive Web Design, FreeCodeCamp
  - https://www.freecodecamp.org/certification/coderprans/responsive-web-design
- Front End Development, FreeCodeCamp
  - https://www.freecodecamp.org/certification/coderprans/legacy-front-end
- APIs and Microservices, FreeCodeCamp
  - https://www.freecodecamp.org/certification/coderprans/apis-and-microservices
- Javascript Algorithms and Data Structures, FreeCodeCamp
  - https://www.freecodecamp.org/certification/coderprans/javascript-algorithms-and-data-structures
- Data Visualization, FreeCodeCamp
  - https://www.freecodecamp.org/certification/coderprans/data-visualization
#+HTML: </div>
#+HTML: </aside>

* Summary
A developer and code enthusiast with ambitions to work for and promote the
open source community and contribute shaping a better future.


* Experience
** Freelancing
#+HTML: <b>Jan 2020 - present</b>

Freelancing for a living. Notable projects include HunarPro and CMS Warje. 
Worked mostly with React and Meta Frameworks based around React like Next 
and Gatsby also explored Svelte.

** Web Developer, Opinta Solutions Pvt. Ltd.
#+HTML: <b>Sep 2018 - Jan 2020 (1 year 5 months)</b> 

Sole developer in a 4 person web solutions startup, tasked with any project 
internal or client. Worked with technologies like React, Node, MongoDB and 
GraphQL.


* Selected Projects
** Hindi Archive
- https://hindiarchive.netlify.app
A React interface over a Python Flask backend using the 'internetarchive'
python library to provide search results for all Hindi items. An approach to
promote the usage of open source resources and the Hindi Language in tech.


** Opinta Solutions
- https://opintasolutions.coderprans.now.sh/
The old official site of Opinta Solutions intended to promote the startup. 
A Gatsby js(React) Headless CMS site with WordPress powered blog backend and 
frontend designed on a BootStrap theme.


** Trawis Connect (incomplete)
- https://trawis-web.coderprans.now.sh/
A social media platform for Travellers. Next js(React) full stack monolith 
using Apollo Client and Apollo-Express GraphQL server backend with MongoDB. 
Although incomplete, phase 1 with user registration, and 
followers/following feature implemented.


** Hunar Pro 
- https://hunarpro.coderprans.vercel.app/
The old official site of Hunar Pro, a startup that provides training and 
kits for World Skills competition. Site build with Next js(React) powered by
Stripe payments for buying kits from the site.


** RSS Reader
- https://rss-reader.coderprans.vercel.app/
A PWA feed reader built on Next js(React) where a user can subscribe to any blog,
register and save their subscriptions. Comes with Dark Mode.


* Education
** freeCodeCamp.org
Full Stack Web Development Certification, Computer Software Engineering
- Jan 2017 - present

** MIT Academy of Engineering, Alandi, Pune
Bachelor of Technology (BTech), Electronics Engineering
- 2016-2020


#+BEGIN_todos
 TODO Add more links
 TODO Add certificate links
 TODO Add projects
 TODO Describe experiences
 TODO Improve summary
 TODO Add relevent skills
#+END_todos
